### PR TITLE
Fix StatsGMS2 so cloud mask is properly applied

### PR DESCRIPTION
**Pull request by fangfy**

### CODE REVIEW

**Review by SpacemanPaul — APPROVED** [review]
Make sense to me.

**Review by emmaai — CHANGES_REQUESTED** [review]
Sorry, it's only to block the merge. I didn't consider the situation of merging from a fork, so the testing workflow was not triggered. I'll need to fix this first before this pr can be merged.

**Comment by fangfy** [comment]
> Sorry, it's only to block the merge. I didn't consider the situation of merging from a fork, so the testing workflow was not triggered. I'll need to fix this first before this pr can be merged.

Thanks @emmaai. I can make a PR from this repo if needed. Do think it's good to be able to merge from a fork so will leave it to you for now.

**Comment by fangfy** [comment]
Replaced by PR #86 made from a branch

**Pull request closed without merging**
